import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { TelegramWebAppContext } from "react-telegram-webapp";
import Script from "next/script";

export default function Home() {
  //const [data, setData] = useState("");
  const scanClicked = function scanClicked() {
    let params = {
      text: "Scan QR code Nikabuy"
    };
    Telegram.WebApp.showScanQrPopup(params,getScanCode);
  };

  var getScanCode=function getScanCode(scan){
    Telegram.WebApp.closeScanQrPopup();
    // setData(scan);
    // getElement('inputBarcode').value = scan;
  }
  return (
    <div className={styles.container}>
      <Script
        src="https://telegram.org/js/telegram-web-app.js"
      />
      <Head>
        <title>Qr - Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to QR Point</h1>
        <div onClick={scanClicked}> Scan</div>
        <hr height="1px" width="40%"/>
        <div className={styles.grid}>
          <Link href="/scan" className={styles.card}>
            <a>
              <h2>Start Scan</h2>
            </a>
          </Link>
        </div>
        <div>{data}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
